# Generated by Django 5.0 on 2023-12-24 10:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('age', models.CharField(help_text='Enter your age', max_length=3)),
                ('profile_pic', models.ImageField(blank=True, help_text='Upload your profile picture', null=True, upload_to='profile_pics/')),
                ('address', models.TextField(blank=True, help_text='Enter your address', null=True)),
                ('city', models.CharField(blank=True, help_text='Enter your city', max_length=50, null=True)),
                ('access_code', models.CharField(help_text='User access code', max_length=6)),
                ('is_verified', models.BooleanField(default=False, help_text='Account verification status')),
                ('trusted_ip', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, null=True, size=None, verbose_name='trusted ip')),
                ('last_online', models.DateTimeField(blank=True, help_text='Last online time', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Branch name', max_length=50, unique=True, verbose_name='branch name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text='Membership name', max_length=50, unique=True, verbose_name='membership name')),
                ('price', models.DecimalField(decimal_places=2, help_text='Membership price', max_digits=10, verbose_name='membership price')),
                ('duration', models.SmallIntegerField(help_text='Membership duration as day', verbose_name='membership duration as day')),
                ('discount', models.SmallIntegerField(help_text='Membership discount as percentage', verbose_name='membership discount as percentage')),
                ('description', models.TextField(help_text='Membership description', verbose_name='membership description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManagerUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('core.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('identity_number', models.CharField(db_index=True, help_text='Enter your identity number', max_length=11)),
                ('phone', models.CharField(db_index=True, help_text='Enter your phone number', max_length=10)),
                ('credit_card', models.JSONField(blank=True, help_text='Patient credit card information', null=True, verbose_name='patient credit card information')),
                ('medical_history', models.JSONField(blank=True, help_text='Patient medical history', null=True, verbose_name='patient medical history')),
                ('medication_history', models.JSONField(blank=True, help_text='Patient medication history', null=True, verbose_name='patient medication history')),
                ('allergies', models.JSONField(blank=True, help_text='Patient allergies', null=True, verbose_name='patient allergies')),
                ('emergency_contact', models.JSONField(blank=True, help_text='Patient emergency contact', null=True, verbose_name='patient emergency contact')),
                ('membership', models.OneToOneField(blank=True, help_text='Patient membership', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='membership', to='core.membership', verbose_name='patient membership')),
            ],
            options={
                'verbose_name': 'patient_user',
                'verbose_name_plural': 'patient_users',
                'db_table': 'patient_user',
            },
            bases=('core.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(db_index=True, help_text='Enter your phone number', max_length=10)),
                ('score', models.SmallIntegerField(db_index=True, default=0, help_text='Doctor satisfaction score', verbose_name='doctor satisfaction score ')),
                ('branch', models.OneToOneField(help_text='Doctor branch', on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='core.branch', verbose_name='doctor branch')),
            ],
            options={
                'verbose_name': 'doctor_user',
                'verbose_name_plural': 'doctor_users',
                'db_table': 'doctor_user',
                'index_together': {('branch', 'score')},
            },
            bases=('core.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
